import type { StudioController } from "@/hooks/use-studio-controller";

export function StudioFeedback({ studio }: { studio: StudioController }) {
  const {
    accessRole, password, leaveTarget, editingEntryBlock, toast, setAccessRole, setPassword,
    setLeaveTarget, setEditingEntryBlock, login, confirmLeave, discardLeave,
  } = studio;
  return <>
    {leaveTarget && <div className="modal-backdrop"><section className="leave-modal" role="dialog" aria-modal="true" aria-labelledby="leave-dialog-title"><span>WRITING IN PROGRESS</span><h2 id="leave-dialog-title">작성 중인 내용이 있습니다.</h2><p>안전하게 임시 저장한 뒤 이동하거나, <strong>마지막 자동 저장 이후 변경</strong>을 버리고 이동할 수 있습니다.</p><div className="leave-modal-actions"><button className="primary-button leave-save-button" onClick={confirmLeave}>임시 저장 후 이동</button><button className="secondary-button leave-continue-button" onClick={() => setLeaveTarget(null)} autoFocus>계속 작성</button><button className="secondary-button leave-discard-button" onClick={() => void discardLeave()}>저장하지 않고 이동</button></div></section></div>}
    {editingEntryBlock && <div className="modal-backdrop" onMouseDown={() => setEditingEntryBlock(null)}><section className="editing-blocked-modal" role="alertdialog" aria-modal="true" aria-labelledby="editing-blocked-title" onMouseDown={(event) => event.stopPropagation()}><span>EDITING LOCKED</span><h2 id="editing-blocked-title">{editingEntryBlock.bookstoreName}에 지금 들어갈 수 없습니다.</h2>{editingEntryBlock.reason === "occupied" ? <p>다른 {editingEntryBlock.activeRole === "html" ? "HTML 편집자" : "소식 입력자"}가 이 책방을 편집 중입니다. 작업이 끝날 때까지 목록에서 기다려 주세요. 활동이 없으면 약 3분 뒤 자동으로 편집할 수 있습니다.</p> : <p>다른 사용자의 편집 상태를 확인하지 못해 안전하게 진입을 멈췄습니다. 네트워크를 확인한 뒤 잠시 후 다시 시도해 주세요.</p>}<div className="editing-blocked-actions"><button className="primary-button" onClick={() => setEditingEntryBlock(null)} autoFocus>확인</button></div></section></div>}
    {accessRole && <div className="modal-backdrop" onMouseDown={() => { setAccessRole(null); setPassword(""); }}><section className="access-modal" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => { setAccessRole(null); setPassword(""); }}>×</button><span>{accessRole === "input" ? "NEWS INPUT ACCESS" : "HTML EDITOR ACCESS"}</span><h2>{accessRole === "input" ? "소식 입력" : "HTML 편집"} 접속</h2><p>{accessRole === "input" ? "책방 소식을 작성하려면 입력자 암호를 입력해 주세요." : "완료된 소식을 HTML로 편집하려면 편집자 암호를 입력해 주세요."}</p><label><span>작업 암호</span><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} onKeyDown={(event) => event.key === "Enter" && login()} autoFocus /></label><button className="primary-button" onClick={login}>{accessRole === "input" ? "소식 입력으로 이동" : "HTML 편집으로 이동"}</button><small>한글·영문 자판 어느 쪽으로 입력해도 됩니다. 접속 상태는 이 탭을 닫거나 로그아웃할 때까지 유지됩니다.</small></section></div>}
    {toast && <div className="toast">✓ {toast}</div>}
  </>;
}
