import { PublishPanel } from "@/components/molecules/PublishPanel";
import type { StudioController } from "@/hooks/use-studio-controller";
import { formatMonth, submissionStatus } from "@/lib/workspace-formatters";

export function HtmlWorkspace({ studio }: { studio: StudioController }) {
  const {
    bookstores, month, htmlView, previewMode, htmlReady, selectedHtmlSubmission,
    selectedHtmlBookstore, generatedCode, generatedPreview, combinedHtml,
    setMonth, setHtmlView, setSelectedSubmissionId, setPreviewMode, setDraggedDigestId,
    setSubmissions, downloadPhotoZip, reorderDigest, updatePublished, notify,
  } = studio;
  return <section className="html-workspace">
    <aside className="html-sidebar"><div><span>HTML WORKSPACE</span><h1>HTML 편집</h1></div><label><span>발행 월</span><input type="month" value={month} onChange={(event) => setMonth(event.target.value)} /></label><nav><button className={htmlView === "individual" ? "active" : ""} onClick={() => setHtmlView("individual")}>개별 HTML <b>{htmlReady.length}</b></button><button className={htmlView === "digest" ? "active" : ""} onClick={() => setHtmlView("digest")}>통합본 만들기</button></nav>{htmlView === "individual" && <div className="ready-list">{htmlReady.map((submission) => { const bookstore = bookstores.find((item) => item.id === submission.bookstoreId); return <button className={selectedHtmlSubmission?.id === submission.id ? "selected" : ""} key={submission.id} onClick={() => setSelectedSubmissionId(submission.id)}><strong>{bookstore?.name}</strong><span>{submission.news.length}개 소식 · {submissionStatus(submission)}</span></button>; })}</div>}</aside>
    {htmlView === "individual" ? <div className="html-main">{selectedHtmlSubmission && selectedHtmlBookstore ? <><div className="html-main-head"><div><span>{formatMonth(month)} · {selectedHtmlBookstore.region}</span><h2>{selectedHtmlBookstore.name}</h2><p>입력 완료된 내용만 표시됩니다.</p></div><div><button className="secondary-button" onClick={() => void downloadPhotoZip(selectedHtmlSubmission, selectedHtmlBookstore, false)}>사진 ZIP</button><button className="primary-button" onClick={() => void downloadPhotoZip(selectedHtmlSubmission, selectedHtmlBookstore, true)}>HTML + 사진 ZIP</button></div></div><div className="html-tabs"><button className={previewMode === "preview" ? "active" : ""} onClick={() => setPreviewMode("preview")}>HTML 미리보기</button><button className={previewMode === "code" ? "active" : ""} onClick={() => setPreviewMode("code")}>HTML 코드</button><button onClick={() => navigator.clipboard.writeText(generatedCode).then(() => notify("HTML 코드를 복사했습니다."))}>HTML 복사</button></div><div className="html-preview">{previewMode === "preview" ? <iframe title={`${selectedHtmlBookstore.name} HTML 미리보기`} srcDoc={`<!doctype html><html><body style="margin:0;background:#eee;padding:24px">${generatedPreview}</body></html>`} /> : <pre>{generatedCode}</pre>}</div><PublishPanel key={selectedHtmlSubmission.id} submission={selectedHtmlSubmission} onPublish={updatePublished} /></> : <div className="empty-state"><h2>입력 완료된 책방이 없습니다.</h2><p>정보 입력자가 입력을 마치면 이곳에 표시됩니다.</p></div>}</div> : <div className="digest-work"><div className="digest-control"><div><span>DIGEST ORDER</span><h2>통합본 수록 순서</h2><p>책방과 포함할 소식을 선택하고 끌어서 순서를 바꿔보세요.</p></div>{htmlReady.map((submission, index) => { const bookstore = bookstores.find((item) => item.id === submission.bookstoreId); return <article key={submission.id} draggable onDragStart={() => setDraggedDigestId(submission.id)} onDragOver={(event) => event.preventDefault()} onDrop={() => reorderDigest(submission.id)}><header><span>⠿</span><div><strong>{index + 1}. {bookstore?.name}</strong><small>{bookstore?.region}</small></div></header>{submission.news.map((news) => <label key={news.id}><input type="checkbox" checked={news.includeInDigest} onChange={() => setSubmissions((current) => current.map((item) => item.id === submission.id ? { ...item, news: item.news.map((entry) => entry.id === news.id ? { ...entry, includeInDigest: !entry.includeInDigest } : entry) } : item))} /><span>{news.title}</span></label>)}</article>; })}</div><div className="digest-output"><div><span>통합 HTML 미리보기</span><button onClick={() => navigator.clipboard.writeText(combinedHtml).then(() => notify("통합 HTML을 복사했습니다."))}>HTML 복사</button></div><iframe title="통합 HTML 미리보기" srcDoc={`<!doctype html><html><body style="margin:0;background:#eee;padding:24px">${combinedHtml}</body></html>`} /></div></div>}
  </section>;
}
